/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
type Image = {
  "@type"?: string;
  "@uri"?: string;
  "@uri150"?: string;
  "@width"?: string;
  "@height"?: string;
};
type Name = {
  "@id"?: string;
  "#text"?: string;
};

export interface Artist {
  images?: {
    image?: Image | Image[];
  };
  id?: string;
  name?: string | null;
  realname?: string | null;
  profile?: string | null;
  data_quality?: string;
  urls?: {
    url?: string | null | (string | null)[];
  };
  namevariations?: {
    name?: string | string[];
  };
  aliases?: null | {
    name?: Name | Name[];
  };
  members?: {
    id?: string | string[];
    name?: Name | Name[];
  };
  groups?: null | {
    name?: Name | Name[];
  };
}
