/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Release {
  images?: {
    image?:
      | {
          "@type"?: string;
          "@uri"?: string;
          "@uri150"?: string;
          "@width"?: string;
          "@height"?: string;
        }
      | {
          "@type"?: string;
          "@uri"?: string;
          "@uri150"?: string;
          "@width"?: string;
          "@height"?: string;
        }[];
  };
  artists?: {
    artist?:
      | {
          id?: string;
          name?: string;
          anv?: null | string;
          join?: null;
          role?: null;
          tracks?: null;
        }
      | {
          id?: string;
          name?: string;
          anv?: null | string;
          join?: string | null;
          role?: null;
          tracks?: null;
        }[];
  };
  title?: string;
  labels?: null | {
    label?:
      | {
          "@name"?: string;
          "@catno"?: string;
          "@id"?: string;
        }
      | {
          "@name"?: string;
          "@catno"?: string;
          "@id"?: string;
        }[];
  };
  extraartists?: null | {
    artist?:
      | {
          id?: string;
          name?: string | null;
          anv?: null | string;
          join?: null;
          role?: string;
          tracks?: null | string;
        }
      | {
          id?: string;
          name?: string;
          anv?: string | null;
          join?: null;
          role?: string;
          tracks?: null | string;
        }[];
  };
  formats?: {
    format?:
      | {
          "@name"?: string;
          "@qty"?: string;
          "@text"?: string;
          descriptions?: {
            description?: string | string[];
          };
        }
      | {
          "@name"?: string;
          "@qty"?: string;
          "@text"?: string;
          descriptions?: {
            description?: (string | {}) | string[];
          };
        }[];
  };
  genres?: {
    genre?: string | string[];
  };
  styles?: {
    style?: string | string[];
  };
  country?: string;
  released?: string | null;
  notes?: string | null;
  data_quality?: string;
  master_id?: {
    "@is_main_release"?: string;
    "#text"?: string;
  };
  tracklist?: null | {
    track?:
      | {
          position?: string | null;
          title?: string;
          duration?: string | null;
          sub_tracks?: {
            track?:
              | {
                  position?: string;
                  title?: string;
                  duration?: null | string;
                  extraartists?: {
                    artist?:
                      | {
                          id?: string;
                          name?: string;
                          anv?: string | null;
                          join?: null;
                          role?: string;
                          tracks?: null;
                        }
                      | {
                          id?: string;
                          name?: string;
                          anv?: null | string;
                          join?: null;
                          role?: string;
                          tracks?: null;
                        }[];
                  };
                }
              | {
                  position?: string;
                  title?: string;
                  duration?: string | null;
                  extraartists?: {
                    artist?:
                      | unknown
                      | {
                          id?: string;
                          name?: string;
                          anv?: null | string;
                          join?: null;
                          role?: string;
                          tracks?: null;
                        }
                      | {
                          id?: string;
                          name?: string;
                          anv?: null | string;
                          join?: null;
                          role?: string;
                          tracks?: null;
                        }[];
                  };
                  artists?: {
                    artist?:
                      | unknown
                      | {
                          id?: string;
                          name?: string;
                          anv?: null | string;
                          join?: null;
                          role?: null;
                          tracks?: null;
                        }
                      | {
                          id?: string;
                          name?: string;
                          anv?: null | string;
                          join?: string | null;
                          role?: null;
                          tracks?: null;
                        }[];
                  };
                }[];
          };
          extraartists?: {
            artist?:
              | {
                  id?: string;
                  name?: string;
                  anv?: null | string;
                  join?: null;
                  role?: string;
                  tracks?: null;
                }
              | {
                  id?: string;
                  name?: string;
                  anv?: string | null;
                  join?: null;
                  role?: string;
                  tracks?: null;
                }[];
          };
          artists?: {
            artist?:
              | {
                  id?: string;
                  name?: string;
                  anv?: string | null;
                  join?: null;
                  role?: null;
                  tracks?: null;
                }
              | {
                  id?: string;
                  name?: string;
                  anv?: string | null;
                  join?: string | null;
                  role?: null;
                  tracks?: null;
                }[];
          };
        }
      | {
          position?: string | null;
          title?: string | null;
          duration?: string | null;
          artists?: {
            artist?:
              | unknown
              | {
                  id?: string;
                  name?: string;
                  anv?: string | null;
                  join?: null;
                  role?: null;
                  tracks?: null;
                }
              | {
                  id?: string;
                  name?: string;
                  anv?: null | string;
                  join?: string | null;
                  role?: null;
                  tracks?: null;
                }[];
          };
          extraartists?: {
            artist?:
              | unknown
              | {
                  id?: string;
                  name?: string;
                  anv?: null | string;
                  join?: null;
                  role?: string;
                  tracks?: null | string;
                }
              | {
                  id?: string;
                  name?: string;
                  anv?: null | string;
                  join?: null;
                  role?: string;
                  tracks?: null | string;
                }[];
          };
          sub_tracks?: {
            track?:
              | unknown
              | {
                  position?: string;
                  title?: string;
                  duration?: string | null;
                  artists?: {
                    artist?:
                      | unknown
                      | {
                          id?: string;
                          name?: string;
                          anv?: null | string;
                          join?: null;
                          role?: null;
                          tracks?: null;
                        }
                      | {
                          id?: string;
                          name?: string;
                          anv?: null | string;
                          join?: string | null;
                          role?: null;
                          tracks?: null;
                        }[];
                  };
                  extraartists?: {
                    artist?:
                      | unknown
                      | {
                          id?: string;
                          name?: string;
                          anv?: null | string;
                          join?: null;
                          role?: string;
                          tracks?: null;
                        }
                      | {
                          id?: string;
                          name?: string;
                          anv?: null | string;
                          join?: null;
                          role?: string;
                          tracks?: null;
                        }[];
                  };
                }
              | {
                  position?: string | null;
                  title?: string;
                  duration?: string | null;
                  extraartists?: {
                    artist?:
                      | unknown
                      | {
                          id?: string;
                          name?: string;
                          anv?: string | null;
                          join?: null;
                          role?: string;
                          tracks?: null;
                        }
                      | {
                          id?: string;
                          name?: string;
                          anv?: null | string;
                          join?: null;
                          role?: string;
                          tracks?: null;
                        }[];
                  };
                  artists?: {
                    artist?:
                      | unknown
                      | {
                          id?: string;
                          name?: string;
                          anv?: string | null;
                          join?: null;
                          role?: null;
                          tracks?: null;
                        }
                      | {
                          id?: string;
                          name?: string;
                          anv?: null | string;
                          join?: string | null;
                          role?: null;
                          tracks?: null;
                        }[];
                  };
                }[];
          };
        }[];
  };
  identifiers?: null | {
    identifier?:
      | {
          "@type"?: string;
          "@description"?: string;
          "@value"?: string;
        }
      | {
          "@type"?: string;
          "@description"?: string;
          "@value"?: string;
        }[];
  };
  videos?: {
    video?:
      | {
          "@src"?: string;
          "@duration"?: string;
          "@embed"?: string;
          title?: string | null;
          description?: string | null;
        }
      | {
          "@src"?: string;
          "@duration"?: string;
          "@embed"?: string;
          title?: string | null;
          description?: string | null;
        }[];
  };
  companies?: null | {
    company?:
      | {
          id?: string;
          name?: string;
          catno?: null | string;
          entity_type?: string;
          entity_type_name?: string;
          resource_url?: string;
        }
      | {
          id?: string;
          name?: string;
          catno?: null | string;
          entity_type?: string;
          entity_type_name?: string;
          resource_url?: string | null;
        }[];
  };
}
